[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xf2ad6c"

[colors.normal]
black = "0x1e2127"
blue = "0x3060ef"
cyan = "0x56b6c2"
green = "0x00bb00"
magenta = "0xc678dd"
red = "0xbf2b37"
white = "0xabb2bf"
yellow = "0xed831e"

[colors.primary]
background = "0x1e2127"
foreground = "0xabb2bf"
